version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - ./backend/src/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data2
    networks:
      - esago-network

  webapi:
    build: ./backend
    restart: no
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - esago-network
    volumes:
      - ./src:/app
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - esago-network
volumes:
  pgdata:


networks:
  esago-network:
    driver: bridge
