version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password!$2
      POSTGRES_DB: esagodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data2
    networks:
      - esago-network

  webapi:
    build: ./backend
    restart: no
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - esago-network
  client:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - esago-network
volumes:
  pgdata:


networks:
  esago-network:
    driver: bridge
