version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password!$2
      POSTGRES_DB: esagodb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data2

volumes:
  pgdata:
